import {
  getPlaylistByCacheKey,
  getPlaylistByPrompt,
  saveArtistMembershipEvidence,
  savePlaylist,
} from '../services/db.js';
import { pathToFileURL } from 'url';

export const SOURCE_PROMPT = '[system] membership evidence backfill v1';

export const MEMBERSHIP_SEED: Array<{ band: string; person: string; role?: string }> = [
  { band: 'The Beatles', person: 'John Lennon', role: 'member' },
  { band: 'The Beatles', person: 'Paul McCartney', role: 'member' },
  { band: 'The Beatles', person: 'George Harrison', role: 'member' },
  { band: 'The Beatles', person: 'Ringo Starr', role: 'member' },
  { band: 'The Rolling Stones', person: 'Mick Jagger', role: 'member' },
  { band: 'The Rolling Stones', person: 'Keith Richards', role: 'member' },
  { band: 'The Rolling Stones', person: 'Charlie Watts', role: 'member' },
  { band: 'The Rolling Stones', person: 'Ronnie Wood', role: 'member' },
  { band: 'The Kinks', person: 'Ray Davies', role: 'member' },
  { band: 'The Kinks', person: 'Dave Davies', role: 'member' },
  { band: 'The Kinks', person: 'Mick Avory', role: 'member' },
  { band: 'The Kinks', person: 'Pete Quaife', role: 'member' },
  { band: 'The Who', person: 'Roger Daltrey', role: 'member' },
  { band: 'The Who', person: 'Pete Townshend', role: 'member' },
  { band: 'The Who', person: 'John Entwistle', role: 'member' },
  { band: 'The Who', person: 'Keith Moon', role: 'member' },
  { band: 'The Doors', person: 'Jim Morrison', role: 'member' },
  { band: 'The Doors', person: 'Ray Manzarek', role: 'member' },
  { band: 'The Doors', person: 'Robby Krieger', role: 'member' },
  { band: 'The Doors', person: 'John Densmore', role: 'member' },
  { band: 'Pink Floyd', person: 'David Gilmour', role: 'member' },
  { band: 'Pink Floyd', person: 'Roger Waters', role: 'member' },
  { band: 'Pink Floyd', person: 'Richard Wright', role: 'member' },
  { band: 'Pink Floyd', person: 'Nick Mason', role: 'member' },
  { band: 'Led Zeppelin', person: 'Robert Plant', role: 'member' },
  { band: 'Led Zeppelin', person: 'Jimmy Page', role: 'member' },
  { band: 'Led Zeppelin', person: 'John Paul Jones', role: 'member' },
  { band: 'Led Zeppelin', person: 'John Bonham', role: 'member' },
  { band: 'Black Sabbath', person: 'Ozzy Osbourne', role: 'member' },
  { band: 'Black Sabbath', person: 'Tony Iommi', role: 'member' },
  { band: 'Black Sabbath', person: 'Geezer Butler', role: 'member' },
  { band: 'Black Sabbath', person: 'Bill Ward', role: 'member' },
  { band: 'Deep Purple', person: 'Ian Gillan', role: 'member' },
  { band: 'Deep Purple', person: 'Ritchie Blackmore', role: 'member' },
  { band: 'Deep Purple', person: 'Roger Glover', role: 'member' },
  { band: 'Deep Purple', person: 'Jon Lord', role: 'member' },
  { band: 'Deep Purple', person: 'Ian Paice', role: 'member' },
  { band: 'Queen', person: 'Freddie Mercury', role: 'member' },
  { band: 'Queen', person: 'Brian May', role: 'member' },
  { band: 'Queen', person: 'Roger Taylor', role: 'member' },
  { band: 'Queen', person: 'John Deacon', role: 'member' },
  { band: 'Genesis', person: 'Peter Gabriel', role: 'member' },
  { band: 'Genesis', person: 'Phil Collins', role: 'member' },
  { band: 'Genesis', person: 'Tony Banks', role: 'member' },
  { band: 'Genesis', person: 'Mike Rutherford', role: 'member' },
  { band: 'Yes', person: 'Jon Anderson', role: 'member' },
  { band: 'Yes', person: 'Chris Squire', role: 'member' },
  { band: 'Yes', person: 'Steve Howe', role: 'member' },
  { band: 'Yes', person: 'Rick Wakeman', role: 'member' },
  { band: 'King Crimson', person: 'Robert Fripp', role: 'member' },
  { band: 'King Crimson', person: 'Greg Lake', role: 'member' },
  { band: 'King Crimson', person: 'Ian McDonald', role: 'member' },
  { band: 'King Crimson', person: 'Michael Giles', role: 'member' },
  { band: 'Roxy Music', person: 'Bryan Ferry', role: 'member' },
  { band: 'Roxy Music', person: 'Brian Eno', role: 'member' },
  { band: 'Roxy Music', person: 'Andy Mackay', role: 'member' },
  { band: 'Roxy Music', person: 'Phil Manzanera', role: 'member' },
  { band: 'The Clash', person: 'Joe Strummer', role: 'member' },
  { band: 'The Clash', person: 'Mick Jones', role: 'member' },
  { band: 'The Clash', person: 'Paul Simonon', role: 'member' },
  { band: 'The Clash', person: 'Topper Headon', role: 'member' },
  { band: 'Talking Heads', person: 'David Byrne', role: 'member' },
  { band: 'Talking Heads', person: 'Tina Weymouth', role: 'member' },
  { band: 'Talking Heads', person: 'Chris Frantz', role: 'member' },
  { band: 'Talking Heads', person: 'Jerry Harrison', role: 'member' },
  { band: 'Joy Division', person: 'Ian Curtis', role: 'member' },
  { band: 'Joy Division', person: 'Bernard Sumner', role: 'member' },
  { band: 'Joy Division', person: 'Peter Hook', role: 'member' },
  { band: 'Joy Division', person: 'Stephen Morris', role: 'member' },
  { band: 'New Order', person: 'Bernard Sumner', role: 'member' },
  { band: 'New Order', person: 'Peter Hook', role: 'member' },
  { band: 'New Order', person: 'Stephen Morris', role: 'member' },
  { band: 'New Order', person: 'Gillian Gilbert', role: 'member' },
  { band: 'The Smiths', person: 'Morrissey', role: 'member' },
  { band: 'The Smiths', person: 'Johnny Marr', role: 'member' },
  { band: 'The Smiths', person: 'Andy Rourke', role: 'member' },
  { band: 'The Smiths', person: 'Mike Joyce', role: 'member' },
  { band: 'Radiohead', person: 'Thom Yorke', role: 'member' },
  { band: 'Radiohead', person: 'Jonny Greenwood', role: 'member' },
  { band: 'Radiohead', person: 'Colin Greenwood', role: 'member' },
  { band: 'Radiohead', person: 'Ed OBrien', role: 'member' },
  { band: 'Radiohead', person: 'Philip Selway', role: 'member' },
  { band: 'Nirvana', person: 'Kurt Cobain', role: 'member' },
  { band: 'Nirvana', person: 'Krist Novoselic', role: 'member' },
  { band: 'Nirvana', person: 'Dave Grohl', role: 'member' },
  { band: 'Sonic Youth', person: 'Thurston Moore', role: 'member' },
  { band: 'Sonic Youth', person: 'Kim Gordon', role: 'member' },
  { band: 'Sonic Youth', person: 'Lee Ranaldo', role: 'member' },
  { band: 'Sonic Youth', person: 'Steve Shelley', role: 'member' },
  { band: 'Oasis', person: 'Noel Gallagher', role: 'member' },
  { band: 'Oasis', person: 'Liam Gallagher', role: 'member' },
  { band: 'Blur', person: 'Damon Albarn', role: 'member' },
  { band: 'Blur', person: 'Graham Coxon', role: 'member' },
  { band: 'Blur', person: 'Alex James', role: 'member' },
  { band: 'Blur', person: 'Dave Rowntree', role: 'member' },
  { band: 'The Stone Roses', person: 'Ian Brown', role: 'member' },
  { band: 'The Stone Roses', person: 'John Squire', role: 'member' },
  { band: 'The Stone Roses', person: 'Mani', role: 'member' },
  { band: 'The Stone Roses', person: 'Reni', role: 'member' },
  { band: 'The Byrds', person: 'Roger McGuinn', role: 'member' },
  { band: 'The Byrds', person: 'David Crosby', role: 'member' },
  { band: 'The Byrds', person: 'Chris Hillman', role: 'member' },
  { band: 'The Byrds', person: 'Gene Clark', role: 'member' },
  { band: 'Crosby, Stills, Nash and Young', person: 'David Crosby', role: 'member' },
  { band: 'Crosby, Stills, Nash and Young', person: 'Stephen Stills', role: 'member' },
  { band: 'Crosby, Stills, Nash and Young', person: 'Graham Nash', role: 'member' },
  { band: 'Crosby, Stills, Nash and Young', person: 'Neil Young', role: 'member' },
  { band: 'The Beach Boys', person: 'Brian Wilson', role: 'member' },
  { band: 'The Beach Boys', person: 'Dennis Wilson', role: 'member' },
  { band: 'The Beach Boys', person: 'Carl Wilson', role: 'member' },
  { band: 'The Beach Boys', person: 'Mike Love', role: 'member' },
  { band: 'The Beach Boys', person: 'Al Jardine', role: 'member' },
  { band: 'Fleetwood Mac', person: 'Stevie Nicks', role: 'member' },
  { band: 'Fleetwood Mac', person: 'Lindsey Buckingham', role: 'member' },
  { band: 'Fleetwood Mac', person: 'Christine McVie', role: 'member' },
  { band: 'Fleetwood Mac', person: 'John McVie', role: 'member' },
  { band: 'Fleetwood Mac', person: 'Mick Fleetwood', role: 'member' },
  { band: 'The Band', person: 'Robbie Robertson', role: 'member' },
  { band: 'The Band', person: 'Levon Helm', role: 'member' },
  { band: 'The Band', person: 'Rick Danko', role: 'member' },
  { band: 'The Band', person: 'Richard Manuel', role: 'member' },
  { band: 'The Band', person: 'Garth Hudson', role: 'member' },
  { band: 'The Stooges', person: 'Iggy Pop', role: 'member' },
  { band: 'The Stooges', person: 'Ron Asheton', role: 'member' },
  { band: 'The Stooges', person: 'Scott Asheton', role: 'member' },
  { band: 'The Stooges', person: 'Dave Alexander', role: 'member' },
  { band: 'Ramones', person: 'Joey Ramone', role: 'member' },
  { band: 'Ramones', person: 'Johnny Ramone', role: 'member' },
  { band: 'Ramones', person: 'Dee Dee Ramone', role: 'member' },
  { band: 'Ramones', person: 'Tommy Ramone', role: 'member' },
  { band: 'The Velvet Underground', person: 'Lou Reed', role: 'member' },
  { band: 'The Velvet Underground', person: 'John Cale', role: 'member' },
  { band: 'The Velvet Underground', person: 'Sterling Morrison', role: 'member' },
  { band: 'The Velvet Underground', person: 'Maureen Tucker', role: 'member' },
];

function ensureSourcePlaylistId(): number {
  const existing = getPlaylistByPrompt(SOURCE_PROMPT) || getPlaylistByCacheKey(SOURCE_PROMPT);
  if (existing) return existing.id;

  const created = savePlaylist(
    SOURCE_PROMPT,
    'System membership evidence seed',
    'Synthetic playlist row used as source for explicit artist membership evidence seeding.',
    '[]',
    JSON.stringify(['system_seed', 'membership'])
  );
  return created.id;
}

export function runMembershipBackfill(): void {
  const sourcePlaylistId = ensureSourcePlaylistId();
  saveArtistMembershipEvidence(sourcePlaylistId, MEMBERSHIP_SEED);

  console.log('[backfill:membership] done');
  console.log(`[backfill:membership] source_playlist_id=${sourcePlaylistId}`);
  console.log(`[backfill:membership] seeded_pairs=${MEMBERSHIP_SEED.length}`);
}

const entryPath = process.argv[1] ? pathToFileURL(process.argv[1]).href : '';
if (entryPath && import.meta.url === entryPath) {
  runMembershipBackfill();
}
